### ISSUE TITLE
Command attempts to load as lesson?

### ISSUE THREAD

**Issue by flseaui** [F1LT3R/dvorak-programmers-tutorial#5]
All commands (-l, -k, h) give this error, it appears it is trying to load them as a lesson. Commands still work after this.
![image](https://user-images.githubusercontent.com/3460531/66708715-ea208880-ed09-11e9-89ea-af6f538e2c58.png)

**Comment by F1LT3R** [comment]
Thanks for reporting. Sorry I missed this.
I've updated with a menu.
Could you tell me if this is a better experience for you?
thanks.
